# Generated by Django 3.2.12 on 2022-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keylogstream',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keylogstream',
            name='stream',
            field=models.TextField(max_length=5000),
        ),
    ]
